spring.application.name=short-url-management-server
server.port=8080

short-url.public-base-url=http://localhost:8081
short-url.cache.redis.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/short_url
spring.datasource.username=short_url
spring.datasource.password=short_url
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
