spring.application.name=short-url-worker-server
server.port=8082

short-url.worker.max-messages=10
short-url.worker.poll-delay-ms=5000

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
